### ISSUE TITLE
Could not find sqlite3-1.3.13 in any of the sources

### ISSUE THREAD

**Issue by sedaf8** [Bhaviktutorials/hackadroid#2]
![image](https://user-images.githubusercontent.com/101340103/157676128-00686df7-6924-4e7a-b005-152b5175dd0a.png)

**Comment by sedaf8** [comment]
I really love your work man 
many stuff here showed that you're really good at making this

**Comment by Bhaviktutorials** [comment]
Thanks a lot bro 
You can solve the error by doing
bundle install
